version: '3'

services:
  lo-app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .env:/var/www/html/.env
      - ./apache_log/:/var/log/apache2/
      - ./apache_php_log/:/var/log/php/
    ports:
      - 8000:80
